### ISSUE TITLE
utiliser les variables SPIP pour les chemins

### ISSUE THREAD

**Issue by maieul** [cahri/spip-iterateur-xls#1]
ne pas mettre 'tmp/cache/' mais utiliser la constante _NOM_TEMPORAIRES_INACCESSIBLES (cf http://www.spip.net/fr_article4636.html) 

permet de résoudre http://contrib.spip.net/iterateur-xls#forum486888

**Comment by maieul** [comment]
en fait c'est _DIR_CACHE qu'il faut

**Comment by maieul** [comment]
gre… combinaison des deux _NOM_TEMPORAIRES_INACCESSIBLES._DIR_CACHE

**Comment by maieul** [comment]
non, _DIR_CACHE suffit

**Comment by julienmru** [comment]
Merci @maieul : c'est résolu :)
